### ISSUE TITLE
Fel bild i trädgårdslistan innan vädret är laddat

### ISSUE THREAD

**Issue by OscarMelin** [projektit/app_prod#5]
![mintradgardfel](https://cloud.githubusercontent.com/assets/7243060/7445440/7c15fb00-f1b3-11e4-8bd1-b0c92044155c.png)

Innan vädret har laddats så ser det ut såhär, är det meningen?

Riktigt snyggt gjort dock! :)

**Comment by Freberg** [comment]
Fixat:)
